server:
  port: 8083

zuul:
  routes:
    course:
      path: /course/**
      url: http://course-edge-service:8081/course/
      # 不过滤cookie等敏感信息
      sensitiveHeaders:
    user:
      path: /user/**
      url: http://user-edge-service:8082/user/
    # 如果只配置path、serviceId有如下简洁写法
#    product: /myProduct/**
#  ignored-patterns:
##    - /myProduct/product/list
##    - /product/product/list
#    - /**/product/listForOrder
#
#
## https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
# VM options: -Dserver.port=9200