service:
  name: user-thrift-service
  port: 7911
spring:
  datasource:
    url: jdbc:mysql://172.16.0.5:3306/db_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
