server:
  name: user-edge-service
  port: 8082

thrift:
  user:
    ip: user-thrift-service
    port: 7911
  message:
    ip: message-service
    port: 9090

spring:
  redis:
    host: 172.16.0.5
    port: 6379