FROM hub.jj.com:8080/micro-service/openjdk:8u181-jre
MAINTAINER Jason 1137829446@qq.com

COPY target/course-dubbo-service-2.0.4.RELEASE.jar /course-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]